.TH set\-default\-soundcard 1 "25 May 2005"

.SH NAME

set\-default\-soundcard \- Set the default ALSA output device in
.B ~/.asoundrc.

.SH SYNOPSIS

.B set\-default\-soundcard
.I number

.B set\-default\-soundcard \-\-check\-markers
.SH DESCRIPTION

If
.B ~/.asoundrc
does not exist yet, it is created with the given sound card number as
default device. The
.B defaults.pcm.card
setting is wrapped in a special comment block "### BEGIN
set-default-soundcard" and "### END set-default-soundcard". 

As long as these markers are present and contain a 
.B defaults.pcm.card
setting, this program is able to change an already existing
onfiguration file. If you manually modified
.B ~/.asoundrc 
and removed the markers, you cannot use this program to change the
configuration any more.

If this program is invoked with
.B \-\-check\-markers\fR, then it only checks whether the
configuration file could be changed (exits with 0 if markers are
intact or the file does not exist, exits with 1 if not).

.SH AUTHOR
This program was written by Martin Pitt <martin.pitt@ubuntu.com> for
Ubuntu. It is freely available under the GPL license.
